# Generated by Django 5.2.6 on 2025-09-05 08:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citoyen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(blank=True, max_length=150, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='citoyens/photos/')),
                ('signature', models.ImageField(blank=True, null=True, upload_to='citoyens/signatures/')),
                ('numero_identite', models.CharField(blank=True, max_length=20, unique=True)),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('valid', 'Valide'), ('invalid', 'Invalide')], default='pending', max_length=10)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='citoyens/qrcodes/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citoyens_crees', to=settings.AUTH_USER_MODEL)),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citoyens_valides', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentJustificatif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('birth_certificate', 'Certificat de naissance'), ('old_id', 'Ancienne carte'), ('passport', 'Passeport'), ('other', 'Autre')], max_length=50)),
                ('fichier', models.FileField(upload_to='citoyens/documents/')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('citoyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.citoyen')),
            ],
        ),
        migrations.CreateModel(
            name='JournalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('date_action', models.DateTimeField(default=django.utils.timezone.now)),
                ('citoyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journaux', to='core.citoyen')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Temoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('relation', models.CharField(help_text='Relation avec le citoyen (ami, parent, voisin, ...)', max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('signature', models.ImageField(upload_to='citoyens/temoins/signatures/')),
                ('citoyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temoins', to='core.citoyen')),
            ],
        ),
    ]
