# Generated by Django 5.2.6 on 2025-09-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_citoyen_documentjustificatif_journalaction_temoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='citoyen',
            name='date_expiration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citoyen',
            name='nationalite',
            field=models.CharField(default='Congolaise', max_length=100),
        ),
        migrations.AddField(
            model_name='citoyen',
            name='postnom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='citoyen',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1),
        ),
    ]
