# Generated by Django 5.2.6 on 2025-09-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_citoyen_date_expiration_citoyen_nationalite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='commune_ou_contree',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_active_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ville_ou_district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
