# Generated by Django 5.2.6 on 2025-09-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customuser_commune_ou_contree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='citoyen',
            name='cellule',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='citoyen',
            name='federation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='citoyen',
            name='province',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='citoyen',
            name='statut_adhesion',
            field=models.CharField(blank=True, choices=[('membre_honneur', "Membre d'honneur"), ('president_federation', 'Président Fédération'), ('president_cellule', 'Président Cellule')], max_length=30, null=True),
        ),
    ]
