# Generated by Django 5.2.6 on 2025-09-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_citoyen_cellule_citoyen_federation_citoyen_province_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citoyen',
            name='statut_adhesion',
            field=models.CharField(choices=[('membre_honneur', "Membre d'honneur"), ('president_federation', 'Président Fédération'), ('president_cellule', 'Président Cellule')], default='membre_honneur', max_length=30),
        ),
    ]
