# Generated by Django 5.2.6 on 2025-09-19 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_citoyen_statut_adhesion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateExpirationfk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='citoyen',
            name='date_expiration_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citoyens', to='core.dateexpirationfk'),
        ),
    ]
