# Generated by Django 5.2.6 on 2025-09-20 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_dateexpirationfk_citoyen_date_expiration_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citoyen',
            name='date_expiration',
        ),
    ]
