# Generated by Django 5.2.6 on 2025-09-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_contribution_news_comment_replycomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='devise',
            field=models.CharField(choices=[('USD', 'Dollar américain (USD)'), ('FC', 'Franc congolais (FC)')], default='FC', max_length=3),
        ),
    ]
